#!/bin/bash
cd /home/tadej_ostanek/cretehotels
~/miniconda3/envs/ota-insight/bin/python '/home/tadej_ostanek/cretehotels/__main__.py'
~/miniconda3/envs/ota-insight/bin/python '/home/tadej_ostanek/cretehotels/google_drive.py'
